[package]
name = "simplify_truths"
version = "0.1.0"
edition = "2021"
authors = ["Martin Berg Alstad"]

[dependencies]
nom = "7.1.3"
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.203", features = ["derive"] }
