openapi: 3.0.0
info:
  title: Simplify Truth Expressions
  version: 0.0.0
tags: []
paths:
  /{exp}:
    get:
      operationId: simplify
      parameters:
        - name: exp
          in: path
          required: true
          schema:
            type: string
        - name: query
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/SimplifyOptions'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplifyResponse'
components:
  schemas:
    Expression:
      oneOf:
        - $ref: '#/components/schemas/Models.ExpressionNot'
        - $ref: '#/components/schemas/Models.ExpressionBinary'
        - $ref: '#/components/schemas/Models.ExpressionAtomic'
    Models.BinaryOperator:
      type: string
      enum:
        - AND
        - OR
        - IMPLICATION
    Models.ExpressionAtomic:
      type: object
      required:
        - atomic
      properties:
        atomic:
          type: string
    Models.ExpressionBinary:
      type: object
      required:
        - left
        - operator
        - right
      properties:
        left:
          $ref: '#/components/schemas/Expression'
        operator:
          $ref: '#/components/schemas/Models.BinaryOperator'
        right:
          $ref: '#/components/schemas/Expression'
    Models.ExpressionNot:
      type: object
      required:
        - not
      properties:
        not:
          $ref: '#/components/schemas/Expression'
    SimplifyOptions:
      type: object
      required:
        - lang
        - simplify
        - caseSensitive
      properties:
        lang:
          type: string
          enum:
            - en
            - nb
          default: en
        simplify:
          type: boolean
          default: true
        caseSensitive:
          type: boolean
          default: false
    SimplifyResponse:
      type: object
      required:
        - before
        - after
        - expression
      properties:
        before:
          type: string
        after:
          type: string
        orderOfOperations:
          type: array
          items:
            type: string
          default: []
        expression:
          $ref: '#/components/schemas/Expression'
